version: "3.8"

services:
  route53-ddns:
    build: .
    image: route53-ddns:latest
    environment:
      - HOSTED_ZONE_ID=Z104486921289MKRWZNSP
      - DNS_RECORD_NAME=home.body-cakes.net
      - RECORD_TYPE=A
      - TTL=60
      - INTERVAL=60
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
secrets:
  aws_access_key_id: 
    external: true
  aws_secret_access_key: 
    external: true
