version: "3.7"
secrets:
  route53_ddns_aws_access_key_id: 
    external: true
  route53_ddns_aws_secret_access_key: 
    external: true
configs:
  route53_ddns_hosted_zone_id:
    external: true
  route53_ddns_domain_name:
    external: true
  route53_ddns_record_type:
    external: true
  route53_ddns_ttl:
    external: true
  route53_ddns_interval:
    external: true
services:
  route53-ddns:
    image: route53-ddns:latest
    secrets:
      - route53_ddns_aws_access_key_id
      - route53_ddns_aws_secret_access_key
    configs:
      - route53_ddns_hosted_zone_id
      - route53_ddns_domain_name
      - route53_ddns_record_type
      - route53_ddns_ttl
      - route53_ddns_interval
